[package]
name = "lightswitch-metadata-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lru = "0.12.4"
nix = { version = "0.29.0", features = ["user"] }
procfs = "0.16.0"
tracing = "0.1.40"
thiserror = "1.0.63"

[build-dependencies]
