[package]
name = "lightswitch-metadata-provider"
version = "0.1.0"
edition = "2021"

[dependencies]
lru = "0.12.4"
nix = { workspace = true, features = ["user", "process"] }
anyhow = { workspace = true }
procfs = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
