[package]
name = "lightswitch-metadata"
version = "0.2.4"
edition = "2024"
description = "Provides metadata used by profilers and debuggers"
license = "MIT"
repository = "https://github.com/javierhonduco/lightswitch"

[dependencies]
lru = { workspace = true }
nix = { workspace = true }
anyhow = { workspace = true }
procfs = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
futures = "0.3"
k8s-openapi = { version = "0.28.0", features = ["latest"] }
kube = { version = "4.2.0", features = ["runtime", "client", "derive"] }
tokio = { version = "1", features = ["rt", "time", "macros"] }
mini-moka = "0.10"
