name: ci
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    ci:
        runs-on: ubuntu-22.04
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
            - uses: DeterminateSystems/flakehub-cache-action@f053b608e8a623da93029482500353079142e628 # v2
            - name: Show nix version
              run: nix --version
            - name: Set up nix dev env
              run: nix develop --command echo 0
            - name: Set nix rustc env var
              run: echo "NIX_RUSTC_VERSION=$(nix develop --ignore-environment --command rustc --version --verbose | tr -d '\n')" >> $GITHUB_ENV
            - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

              with:
                  key: ${{ env.NIX_RUSTC_VERSION }}
            - name: Run `cargo check`
              run: nix develop --ignore-environment --command cargo check
            - name: Run `cargo clippy`
              run: nix develop --command cargo clippy --workspace --all-targets -- -D warnings
            - name: Run `cargo test`
              run: nix develop --command cargo test --workspace
            - name: Run `cargo fmt`
              run: nix develop --command cargo fmt --check
            - name: Run `cargo rustdoc`
              run: nix develop --command cargo rustdoc --all-features -- -Zunstable-options --check -Dwarnings
            - name: Run `nix fmt`
              run: nix fmt -- --check .
            - name: Run `cargo shear`
              run: nix develop --command cargo shear

    ci-arm:
        runs-on: ubuntu-22.04-arm
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
            - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
            - uses: DeterminateSystems/flakehub-cache-action@f053b608e8a623da93029482500353079142e628 # v2
            - name: Set up nix dev env
              run: nix develop --command echo 0
            - name: Set nix rustc env var
              run: echo "NIX_RUSTC_VERSION=$(nix develop --ignore-environment --command rustc --version --verbose | tr -d '\n')" >> $GITHUB_ENV
            - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
              with:
                  key: ${{ env.NIX_RUSTC_VERSION }}
            - name: Run `cargo check`
              run: nix develop --ignore-environment --command cargo check
            - name: Run `cargo test`
              run: nix develop --command cargo test --workspace
