name: build container image
on:
  pull_request:
  push:
      branches:
        - main

jobs:
  container:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: DeterminateSystems/flakehub-cache-action@8ceb5534cc3f9ba4f1083af0ab4ce21b6c19217f # v2

    - name: Show nix version
      run: nix --version
    - name: Set up nix dev env
      run: nix develop --command echo 0
    - name: Build container image
      run: nix build .#container
    - name: Push container image on commits to main
      if: ${{ github.repository_owner == 'javierhonduco' && github.ref_name == 'main' }}
      run: |
        export CONTAINERS_REGISTRIES_CONF=/dev/null
        nix develop --ignore-environment --keep-env-var CONTAINERS_REGISTRIES_CONF --command skopeo copy --dest-creds="${{ github.repository_owner }}:${{ github.token }}" docker-archive:./result docker://ghcr.io/javierhonduco/lightswitch:main-${{ github.sha }}
