name: static build and upload
on:
  pull_request:
  push:
      branches:
        - main

jobs:
  static-build:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
        contents: read

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: DeterminateSystems/flakehub-cache-action@771f7cc21370bb0b97ff0c5dc442073f9f45ebda # v2

    - name: Show nix version
      run: nix --version

    - name: Set up nix dev env
      run: nix develop --command echo 0

    - name: Set nix rustc env var
      run: echo "NIX_RUSTC_VERSION=$(nix develop --ignore-environment --command rustc --version --verbose | tr -d '\n')" >> $GITHUB_ENV

    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        key: ${{ env.NIX_RUSTC_VERSION }}

    - name: Build `lightswitch` statically linked with glibc
      run: nix develop --ignore-environment --command bash -c 'RUSTFLAGS="-C target-feature=+crt-static" cargo build --release --target x86_64-unknown-linux-gnu'

    - name: Show size
      run: ls -lah target/x86_64-unknown-linux-gnu/release/lightswitch

    - name: Run `ldd`
      run: ldd target/x86_64-unknown-linux-gnu/release/lightswitch

    - name: Upload binary
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: actions/upload-artifact@main
      with:
        name: lightswitch-x86_64
        path: target/x86_64-unknown-linux-gnu/release/lightswitch