name: vmtests
on:
  pull_request:
  push:
      branches:
        - main

jobs:
  vmtests:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
        contents: read

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
    - uses: DeterminateSystems/flakehub-cache-action@4d48cd3cda2f381a3006ff800e1c1ca0c9809159 # v2

    - name: Install system dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update && sudo apt-get -y install --no-install-recommends qemu-system-x86 qemu-guest-agent

    - name: Show nix version
      run: nix --version

    - name: Run kernel tests
      run: nix run .#vmtest